#!/bin/sh
path=`readlink -f $0`
base=`dirname $path`
lib=$base/lib
export QT_ACCESSIBILITY=0 # qt-at-spi causes crashes and performance issues in various distros, so disable it
export LD_LIBRARY_PATH=$lib:$LD_LIBRARY_PATH
export MAGICK_HOME=$base
export MAGICK_CONFIGURE_PATH=$lib/ImageMagick-6.7.6/config
export MAGICK_CODER_MODULE_PATH=$lib/ImageMagick-6.7.6/modules-Q16/coders
export MAGICK_CODER_FILTER_PATH=$lib/ImageMagick-6.7.6/modules-Q16/filters
exec $base/bin/ebook-edit "$@"
